user:
  defaultPwd: root@1

seata:
  enabled: true
  application-id: seata-server
  tx-service-group: my_test_tx_group
  service:
    vgroup-mapping:
      my_test_tx_group: default
  # 一定要是false
  enable-auto-data-source-proxy: false
  config:
    type: nacos
    nacos:
      serverAddr: 172.25.136.236:8847
      namespace: dc84bcb7-2154-4b46-a4dc-0df145e8feb6
      group: SEATA_GROUP
      userName: "nacos"
      password: "nacos"
  registry:
    type: nacos
    nacos:
      server-addr: 172.25.136.236:8847
      namespace: dc84bcb7-2154-4b46-a4dc-0df145e8feb6
      application: seata-server
      userName: "nacos"
      password: "nacos"