springdoc:
  use-fqn: true
  api-docs:
    resolve-schema-properties: true
    path: /v3/api-docs
  packagesToScan: com.tscredit.origin.main.action
  #  pathsToMatch: /v1, /api/balance/**
  swagger-ui:
    path: /doc
    default-models-expand-depth: -1
object:
  version: @project.version@
  artifactId: @project.artifactId@
spring:
  cloud:
    sentinel:
      eager: true
      transport:
        dashboard: 172.25.136.236:9988   #sentinel控制台的请求地址
        port: 9988
        clientIp: 172.25.136.65
      datasource:
        # 名称随意
        flow:
          nacos:
            server-addr: @nacos.addr@
            namespace: @nacos.namespace@
            group-id: @nacos.config.group@
            dataId: @artifactId@-sentinel
            # 规则类型，取值见：
            # org.springframework.cloud.alibaba.sentinel.datasource.RuleType
            rule-type: flow
    loadbalancer:
      retry:
        # 该参数用来开启或关闭重试机制，默认是开启
        enabled: false
  jta:
    atomikos:
      datasource:
        xa-data-source-class-name:
management:
  endpoints:
    web:
      exposure:
        include: '*'

